const BGG_CATEGORY_ES: Record<string, string> = {
  'Abstract Strategy': 'Estrategia abstracta',
  'Action / Dexterity': 'Acción / Destreza',
  'Adventure': 'Aventura',
  'Age of Reason': 'Ilustración',
  'American Civil War': 'Guerra de Secesión',
  'American Indian Wars': 'Guerras indias',
  'American Revolutionary War': 'Independencia de EE. UU.',
  'American West': 'Lejano Oeste',
  'Ancient': 'Antigüedad',
  'Animals': 'Animales',
  'Arabian': 'Mundo árabe',
  'Aviation / Flight': 'Aviación',
  'Bluffing': 'Faroleo',
  'Book': 'Libro',
  'Card Game': 'Juego de cartas',
  "Children's Game": 'Infantil',
  'City Building': 'Construcción de ciudades',
  'Civil War': 'Guerra civil',
  'Civilization': 'Civilización',
  'Collectible Components': 'Coleccionable',
  'Comic Book / Strip': 'Cómic',
  'Deduction': 'Deducción',
  'Dice': 'Dados',
  'Economic': 'Económico',
  'Educational': 'Educativo',
  'Electronic': 'Electrónico',
  'Environmental': 'Medio ambiente',
  'Expansion for Base-game': 'Expansión',
  'Exploration': 'Exploración',
  'Fan Expansion': 'Expansión fan',
  'Fantasy': 'Fantasía',
  'Farming': 'Granja',
  'Fighting': 'Combate',
  'Game System': 'Sistema de juego',
  'Horror': 'Terror',
  'Humor': 'Humor',
  'Industry / Manufacturing': 'Industria',
  'Korean War': 'Guerra de Corea',
  'Mafia': 'Mafia',
  'Math': 'Matemáticas',
  'Mature / Adult': 'Adultos',
  'Maze': 'Laberinto',
  'Medical': 'Medicina',
  'Medieval': 'Medieval',
  'Memory': 'Memoria',
  'Miniatures': 'Miniaturas',
  'Modern Warfare': 'Guerra moderna',
  'Movies / TV / Radio theme': 'Cine / TV / Radio',
  'Murder/Mystery': 'Misterio / Asesinato',
  'Music': 'Música',
  'Mythology': 'Mitología',
  'Napoleonic': 'Napoleónico',
  'Nautical': 'Náutico',
  'Negotiation': 'Negociación',
  'Novel-based': 'Basado en novela',
  'Number': 'Números',
  'Party Game': 'Juego de fiesta',
  'Pike and Shot': 'Picas y arcabuces',
  'Pirates': 'Piratas',
  'Political': 'Política',
  'Post-Napoleonic': 'Posnapoleónico',
  'Prehistoric': 'Prehistoria',
  'Print & Play': 'Imprime y juega',
  'Puzzle': 'Puzle',
  'Racing': 'Carreras',
  'Real-time': 'Tiempo real',
  'Religious': 'Religión',
  'Renaissance': 'Renacimiento',
  'Science Fiction': 'Ciencia ficción',
  'Space Exploration': 'Exploración espacial',
  'Spies/Secret Agents': 'Espías',
  'Sports': 'Deportes',
  'Territory Building': 'Control de territorio',
  'Trains': 'Trenes',
  'Transportation': 'Transporte',
  'Travel': 'Viajes',
  'Trivia': 'Preguntas y respuestas',
  'Video Game Theme': 'Temática videojuego',
  'Vietnam War': 'Guerra de Vietnam',
  'Wargame': 'Wargame',
  'Word Game': 'Palabras',
  'World War I': 'Primera Guerra Mundial',
  'World War II': 'Segunda Guerra Mundial',
  'Zombies': 'Zombis',
};

export function categoryEs(name: string): string {
  return BGG_CATEGORY_ES[name] ?? name;
}
